#ifndef PROJECT_INCLUDE_FORMAT_H_
#define PROJECT_INCLUDE_FORMAT_H_

#include <string.h>
#include <stdio.h>

enum size {
    MAX_SIZE_FORMAT_STRING = 80,
    NAME_SIZE = 20,
    SURNAME_SIZE = 20,
    ADDRESS_SIZE = 30,
    TEL_NUMBER_SIZE = 15
};

enum format {
FORMAT_TO_SCANF_CLIENT_BASE,
FORMAT_TO_FPRINTF_CLIENT_BASE,
FORMAT_TO_FPRINTF_TRANSACTION_BASE
};

enum format_of_write_to_file {
    ID_FORMAT = 12,
    NAME_FORMAT_CLIENT_BASE = 11,
    NAME_FORMAT_TRANSACTION_BASE = 3,
    SURNAME_FORMAT = 11,
    ADDRESS_FORMAT = 16,
    TEL_NUMBER_FORMAT = 20,
    INDEBTEDNESS_FORMAT_CLIENT_BASE = 12,
    INDEBTEDNESS_PRECISION_CLIENT_BASE = 2,
    INDEBTEDNESS_FORMAT_TRANSACTION_BASE = 6,
    INDEBTEDNESS_PRECISION_TRANSACTION_BASE = 2
};

void menu(int menu_type);

#endif  //  PROJECT_INCLUDE_FORMAT_H_
